address = "localhost"
port = 5555

[signals.signal0]
    	id = 10
    	type = "gen"
        amount = 100000000
    	gen_type = "normal"

    		[signals.signal0.params]
    		mean = 0.0 # Sets the mean
    		std = 1.0 # Sets the standard deviation

#[signals.signal1]
#    	id = 12
#    	type = "gen"
#        amount = 100000
#    	gen_type = "normal"
#
#    		[signals.signal1.params]
#    		mean = 50.0 # Sets the mean
#    		std = 10.0 # Sets the standard deviation
