protocol = "tcp"
address = "localhost"
port = 5556

[clients.client0]
    	id = 12
    	type = "gen"
        amount = 25000000
    	gen_type = "normal"

    		[clients.client0.params]
    		mean = 0.0 # Sets the mean
    		std = 1.0 # Sets the standard deviation

[clients.client1]
    	id = 13
    	type = "gen"
        amount = 25000000
    	gen_type = "normal"

    		[clients.client1.params]
    		mean = 50.0 # Sets the mean
    		std = 10.0 # Sets the standard deviation
