protocol = "tcp"
address = "localhost"
port = 5556

[clients.client0]
    	id = 10
    	type = "gen"
        amount = 50000000
    	gen_type = "normal"

    		[clients.client0.params]
    		mean = 0.0 # Sets the mean
    		std = 1.0 # Sets the standard deviation

#[clients.client1]
#    	id = 12
#    	type = "gen"
#        amount = 100000
#    	gen_type = "normal"
#
#    		[clients.client1.params]
#    		mean = 50.0 # Sets the mean
#    		std = 10.0 # Sets the standard deviation
