address = "localhost"
port = 5555

[signals.signal0]
    	id = 10
    	type = "gen"
        amount = 25000000
    	gen_type = "normal"

    		[signals.signal0.params]
    		mean = 0.0 # Sets the mean
    		std = 1.0 # Sets the standard deviation

[signals.signal1]
    	id = 11
    	type = "gen"
        amount = 25000000
    	gen_type = "normal"

    		[signals.signal1.params]
    		mean = 50.0 # Sets the mean
    		std = 10.0 # Sets the standard deviation
[signals.signal2]
    	id = 12
    	type = "gen"
        amount = 25000000
    	gen_type = "normal"

    		[signals.signal2.params]
    		mean = 5.0 # Sets the mean
    		std = 3.0 # Sets the standard deviation

[signals.signal3]
    	id = 13
    	type = "gen"
        amount = 25000000
    	gen_type = "normal"

    		[signals.signal3.params]
    		mean = 70.0 # Sets the mean
    		std = 20.0 # Sets the standard deviation
